[build]
  publish = "site"
  command = "npm install"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
